Giane/[01] Refactor: migrate to androidx
CheesecakeLabs/cheesecake-core-android pull request #11
Opened 2020-03-06 13:35 UTC by gianebinotto

Migrate lib core to androidx

2020-03-06 18:33 UTC, guilucas07 requested changes

2020-03-06 18:33 UTC, guilucas07 commented on app/src/androidTest/java/com/rubenshardt/cheesecakecoreexample/ExampleInstrumentedTest.kt
> +        val appContext = androidx.test.InstrumentationRegistry.getTargetContext()
add this import at the top of file, like "import androidx.test.ext.junit.runners.AndroidJUnit4"

2020-03-06 18:33 UTC, guilucas07 commented on core/src/androidTest/java/io/cheesecakelabs/core/ExampleInstrumentedTest.java
> +        Context appContext = androidx.test.InstrumentationRegistry.getTargetContext();
add this import at the top of file, like "import androidx.test.ext.junit.runners.AndroidJUnit4"

2020-03-06 18:33 UTC, guilucas07 commented on retrofit/src/androidTest/java/io/cheesecakelabs/retrofit/ExampleInstrumentedTest.java
> +        Context appContext = androidx.test.InstrumentationRegistry.getTargetContext();
add this import at the top of file, like "import androidx.test.ext.junit.runners.AndroidJUnit4"
Are these files necessary?

2020-03-09 14:39 UTC, diegohkd requested changes
Same as Gui

2020-03-09 16:55 UTC, gianebinotto commented on retrofit/src/androidTest/java/io/cheesecakelabs/retrofit/ExampleInstrumentedTest.java
> +        Context appContext = androidx.test.InstrumentationRegistry.getTargetContext();
I just kept them because they already existed.

2020-03-09 17:37 UTC, diegohkd approved these changes

2020-03-09 17:40 UTC, guilucas07 commented on retrofit/src/androidTest/java/io/cheesecakelabs/retrofit/ExampleInstrumentedTest.java
> +        Context appContext = androidx.test.InstrumentationRegistry.getTargetContext();
so, can be removed, right?

2020-03-09 17:44 UTC, gianebinotto commented on retrofit/src/androidTest/java/io/cheesecakelabs/retrofit/ExampleInstrumentedTest.java
> +        Context appContext = androidx.test.InstrumentationRegistry.getTargetContext();
Done

2020-03-09 17:54 UTC, guilucas07 approved these changes

2020-04-15 00:05 UTC, RubensHardt approved these changes

2020-04-15 01:16 UTC, merged