Giane/[02] Feat: Masks extension
CheesecakeLabs/cheesecake-core-android pull request #9
Opened 2019-09-08 16:44 UTC by gianebinotto

Extension to handle masks for credit card, CPF, CEP, cellphone or any other pattern

2019-09-09 14:42 UTC, guilucas07 approved these changes

2019-09-09 15:34 UTC, diegohkd requested changes

2019-09-09 15:34 UTC, diegohkd commented on core/src/main/java/io/cheesecakelabs/core/utils/extensions/EditText+Maks.kt
> +    mask("#### #### #### ####")
What if the card has more than 16 digits?

2019-09-09 15:34 UTC, diegohkd commented on core/src/main/java/io/cheesecakelabs/core/utils/extensions/EditText+Maks.kt
> +    else mask("(##) #########")
What if the area code has 3 digits?

2019-09-09 15:34 UTC, diegohkd commented on core/src/main/java/io/cheesecakelabs/core/utils/extensions/EditText+Maks.kt
> +            val str = s.toString().replace("[./() \\-+]".toRegex(), "")
I don't know if it's a good idea to do something so generic here. Maybe some masks would need one of this characters. One option is to have different TextWatchers for each mask. I remember seeing this on Nobis project: 
https://github.com/CheesecakeLabs/local-android/tree/dev/app/src/main/java/com/nobis/app/utils/text_watchers

2019-09-12 18:03 UTC, gianebinotto commented on core/src/main/java/io/cheesecakelabs/core/utils/extensions/EditText+Maks.kt
> +    mask("#### #### #### ####")
Couldn't the general mask be used in this case?

2019-09-30 13:52 UTC, RubensHardt approved these changes

2019-09-30 17:00 UTC, ximendes-regis approved these changes

2020-01-26 23:18 UTC, merged